[package]
name = "rstml-component-axum"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", default-features = true, features = ["headers"] }
rstml-component = { version = "0.0.0", path = "../../" }
