name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      # Always run main branch builds to completion.
      fail-fast: ${{ github.event_name == 'pull_request' ||
        (github.ref != 'refs/heads/main' &&
        !startsWith(github.ref, 'refs/tags/')) }}
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Run sccache-cache
        if: github.repository == 'YoloDev/rstml-component'
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Configure sccache
        if: github.repository == 'YoloDev/rstml-component'
        shell: bash
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
          echo "SCCACHE_BUCKET=${{ vars.SCCACHE_BUCKET }}" >> $GITHUB_ENV
          echo "SCCACHE_REGION=${{ vars.SCCACHE_REGION }}" >> $GITHUB_ENV
          echo "SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.SCCACHE_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SCCACHE_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Lint
        run: cargo clippy --all -- -D warnings

      - name: Run tests
        run: cargo test --workspace

      - name: Create docs
        if: matrix.os == 'ubuntu-latest'
        run: cargo doc --workspace

      - name: Save docs as artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: target/doc
          retention-days: 1

  publish-docs:
    name: Publish docs
    needs: test
    runs-on: ubuntu-latest
    if: github.repository == 'YoloDev/rstml-component' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
